backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads" # Carpeta donde se guardan imágenes en el repositorio
public_folder: "/assets/images/uploads" # Ruta pública de acceso a las imágenes

collections:
  - name: "posts"
    label: "Entradas del Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Fecha"
        name: "date"
        widget: "datetime"
      - label: "Contenido"
        name: "body"
        widget: "markdown"
